#ifndef __RTTI_H__
# define __RTTI_H__

typedef enum	RTTIType
{
  __RTTI_COLORBUFFER,
  __RTTI_DEPTHBUFFER,
  __RTTI_NORMALBUFFER,
  __RTTI_POINTBUFFER,
  __RTTI_LOCALPOINTBUFFER,
  __RTTI_RAYBUFFER,
  __RTTI_LIGHTBUFFER,
  __RTTI_MATBUFFER,
  __RTTI_BOOLBUFFER,

  __RTTI_REGULAR,
  __RTTI_PURERANDOM,
  __RTTI_JITTERED,
  __RTTI_MULTIJITTERED,

  __RTTI_AMBIENT,
  __RTTI_POINTLIGHT,
  __RTTI_AREALIGHT,
  __RTTI_ENVIRONMENTLIGHT,
  __RTTI_VPL,

  __RTTI_REFLECTIVE,
  __RTTI_GLOSSYREFLECTIVE,
  __RTTI_PHONG,
  __RTTI_MATTE,
  __RTTI_TRANSPARENT,
  __RTTI_EMISSIVE,
  __RTTI_CHECKER,
  __RTTI_NOISE,
  __RTTI_BUMP,
  __RTTI_IMGTEXTURE,

  __RTTI_GRID,
  __RTTI_MESH,
  __RTTI_TRIANGLE,

  __RTTI_OVERSAMPLINGRENDERPASS,
  __RTTI_FIRSTRENDERPASS,
  __RTTI_LIGHTRENDERPASS,
  __RTTI_SHADOWRENDERPASS,
  __RTTI_AORENDERPASS,
  __RTTI_SHADERGBRENDERPASS,
  __RTTI_TRANSPARENCYRENDERPASS,
  __RTTI_REFLECTIONRENDERPASS,
  __RTTI_AREALIGHTRENDERPASS,
  __RTTI_INSTRADIOSITYRENDERPASS,
  __RTTI_SSAORENDERPASS,
  __RTTI_TEXTURERENDERPASS,
  __RTTI_BUMPRENDERPASS,
  __RTTI_PATHTRACINGRENDERPASS,
  __RTTI_GAMMARENDERPASS,
  __RTTI_TONEMAPPINGRENDERPASS,
  __RTTI_NEGATIVERENDERPASS
}		RTTIType;

#endif /* !__RTTI_H__ */
